### ISSUE TITLE
Hellhounds break boss triggers

### ISSUE THREAD

**Issue by ghost** [swc132994/BD64-VoH_game#12]
During a playthrough of E1M8, a Hellhound spawned in place of the Baron, but when I killed both the Hellhound and the Baron, the boss trigger door didn't work at all. I had to use noclip to beat the level. I checked the code for both Hellhounds and they lacked the BossDeath flag along with the A_BossDeath function.

**Comment by swc132994** [comment]
In this case the A_BossDeath won't work. These monsters are spawned through a separate spawner.
The spawner holds the BossDeath flag instead of the monster. When the monster dies, it triggers the A_KillMaster which kills the spawner to allow the map to progress.

It looks like someone has edited the spawner so this link is broken. I shall repair it.

**Comment by swc132994** [comment]
This is now fixed and tested. I just needed to add the highlighted line to the spawner.
![image](https://github.com/swc132994/BD64game_v2.666/assets/10770202/d916f59f-388b-4a27-9245-99b7c5911a74)

Give it a whirl and let me know.

**Comment by swc132994** [comment]
Hello,

Can we close this issue?

**Comment by swc132994** [comment]
After testing a number of times, I haven't encountered this problem since.
